if SERVER then AddCSLuaFile() end

HG_SEAL_CONFIG = HG_SEAL_CONFIG or {
    MAX_HEALTH = 100,
    MAX_BLOOD_ML = 1200,
    FATAL_BLOOD_LOSS_ML = 500,
    BLEED_CLOT_RATE = 0.02,
    CORPSE_LIFETIME = 15,
    CORPSE_FADE_TIME = 3,
    THROW_SPEED = 760,
    THROW_DAMAGE = 19,
    THROW_MIN_DAMAGE_SPEED = 300,
    THROW_DAMAGE_WINDOW = 2,
    THROW_REFERENCE_MASS = 8
}
